from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

SKIDL_lib_version = '0.0.1'

panel_lib = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'74HC595', 'dest':TEMPLATE, 'tool':SKIDL, 'tool_version':'kicad', 'PN':'SN74HC595DB-MF', '_aliases':Alias({'74AHCT595', '74LS595', '74AHC595', '74HCT595'}), 'Manf':'Texas Instruments', 'value_str':'74HC595', 'keywords':'TTL SR 3State', 'datasheet':'http://www.ti.com/lit/gpn/sn74ls595', '_match_pin_regex':False, 'description':'8-bit serial in/out Shift Register 3-State Outputs', 'ref_prefix':'U', 'num_units':1, 'fplist':['DIP*W7.62mm*', 'SOIC*3.9x9.9mm*P1.27mm*', 'TSSOP*4.4x5mm*P0.65mm*', 'SOIC*5.3x10.2mm*P1.27mm*', 'SOIC*7.5x10.3mm*P1.27mm*'], 'do_erc':True, 'aliases':Alias({'74AHCT595', '74LS595', '74AHC595', '74HCT595'}), 'pin':None, 'footprint':'glabs_misc:TSSOP-16_slim', 'pins':[
            Pin(num='1',name='QB',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='10',name='~SRCLR',func=Pin.types.INPUT,do_erc=True),
            Pin(num='11',name='SRCLK',func=Pin.types.INPUT,do_erc=True),
            Pin(num='12',name='RCLK',func=Pin.types.INPUT,do_erc=True),
            Pin(num='13',name='~OE',func=Pin.types.INPUT,do_erc=True),
            Pin(num='14',name='SER',func=Pin.types.INPUT,do_erc=True),
            Pin(num='15',name='QA',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='16',name='VCC',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='2',name='QC',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='3',name='QD',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='4',name='QE',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='5',name='QF',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='6',name='QG',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='7',name='QH',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='8',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='9',name="QH'",func=Pin.types.OUTPUT,do_erc=True)] }),
        Part(**{ 'name':'TLC59025', 'dest':TEMPLATE, 'tool':SKIDL, 'tool_version':'kicad', 'PN':'TLC59025IDBQR', 'Manf':'Texas Instruments', 'value_str':'TLC59025', 'keywords':'', 'datasheet':'', '_match_pin_regex':False, 'description':'', 'ref_prefix':'U', 'num_units':1, 'fplist':[], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'glabs_misc:SSOP-24_slim', 'pins':[
            Pin(num='1',name='GND',func=Pin.types.UNSPEC,do_erc=True),
            Pin(num='10',name='~OUT5',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='11',name='~OUT6',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='12',name='~OUT7',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='13',name='~OUT8',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='14',name='~OUT9',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='15',name='~OUT10',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='16',name='~OUT11',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='17',name='~OUT12',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='18',name='~OUT13',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='19',name='~OUT14',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='2',name='SDI',func=Pin.types.INPUT,do_erc=True),
            Pin(num='20',name='~OUT15',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='21',name='~OE',func=Pin.types.INPUT,do_erc=True),
            Pin(num='22',name='SDO',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='23',name='R-EXT',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='24',name='VDD',func=Pin.types.UNSPEC,do_erc=True),
            Pin(num='3',name='CLK',func=Pin.types.INPUT,do_erc=True),
            Pin(num='4',name='LE',func=Pin.types.INPUT,do_erc=True),
            Pin(num='5',name='~OUT0',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='6',name='~OUT1',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='7',name='~OUT2',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='8',name='~OUT3',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='9',name='~OUT4',func=Pin.types.OUTPUT,do_erc=True)] }),
        Part(**{ 'name':'LED_ARGB', 'dest':TEMPLATE, 'tool':SKIDL, 'tool_version':'kicad', 'PN':'FM-B2020RGBA-HG', 'Manf':'Foshan NationStar Optoelectronics', 'value_str':'LED_ARGB', 'keywords':'LED RGB diode', 'datasheet':'~', '_match_pin_regex':False, 'description':'RGB LED, anode/red/green/blue', 'ref_prefix':'D', 'num_units':1, 'fplist':['LED*', 'LED_SMD:*', 'LED_THT:*'], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'glabs_led:led_rbag_2020', 'pins':[
            Pin(num='1',name='A',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='RK',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='GK',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='BK',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'Q_PMOS_GSD', 'dest':TEMPLATE, 'tool':SKIDL, 'tool_version':'kicad', 'PN':'PJ2301-AU_R1_000A1', 'Manf':'PANJIT International', 'value_str':'Q_PMOS_GSD', 'keywords':'transistor PMOS P-MOS P-MOSFET', 'datasheet':'~', '_match_pin_regex':False, 'description':'P-MOSFET transistor, gate/source/drain', 'ref_prefix':'Q', 'num_units':1, 'fplist':[], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'Package_TO_SOT_SMD:SOT-23', 'pins':[
            Pin(num='1',name='G',func=Pin.types.INPUT,do_erc=True),
            Pin(num='2',name='S',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='D',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'Conn_01x20_Shielded', 'dest':TEMPLATE, 'tool':SKIDL, 'tool_version':'kicad', 'PN':'FH12-20S-0.5SVA(54)', 'Manf':'Hirose Electric Co Ltd', 'value_str':'Conn_01x20_Shielded', 'keywords':'connector', 'datasheet':'~', '_match_pin_regex':False, 'description':'Generic shielded connector, single row, 01x20, script generated (kicad-library-utils/schlib/autogen/connector/)', 'ref_prefix':'J', 'num_units':1, 'fplist':['Connector*:*_1x??-1SH*'], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'glabs_conn:FH12-20S-0.5SVA(54)', 'pins':[
            Pin(num='1',name='Pin_1',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='10',name='Pin_10',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='11',name='Pin_11',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='12',name='Pin_12',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='13',name='Pin_13',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='14',name='Pin_14',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='15',name='Pin_15',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='16',name='Pin_16',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='17',name='Pin_17',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='18',name='Pin_18',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='19',name='Pin_19',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='Pin_2',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='20',name='Pin_20',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='Pin_3',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='Pin_4',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='5',name='Pin_5',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='6',name='Pin_6',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='7',name='Pin_7',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='8',name='Pin_8',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='9',name='Pin_9',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='SH',name='Shield',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'CP1', 'dest':TEMPLATE, 'tool':SKIDL, 'tool_version':'kicad', 'PN':'UWX1C101MCL1GB', 'Manf':'Nichicon', 'value_str':'CP1', 'keywords':'cap capacitor', 'datasheet':'~', '_match_pin_regex':False, 'description':'Polarized capacitor, US symbol', 'ref_prefix':'C', 'num_units':1, 'fplist':['CP_*'], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'Capacitor_SMD:CP_Elec_5x3.9', 'pins':[
            Pin(num='1',name='~',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='~',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'tool_version':'kicad', 'PN':'CL05B104KP5NNNC', 'Manf':'Samsung Electro-Mechanics', 'value_str':'100nF', 'keywords':'cap capacitor', 'datasheet':'~', '_match_pin_regex':False, 'description':'Unpolarized capacitor', 'ref_prefix':'C', 'num_units':1, 'fplist':['C_*'], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'pins':[
            Pin(num='1',name='~',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='~',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'tool_version':'kicad', 'PN':'', 'Manf':'Yageo', 'value_str':'0', 'keywords':'R res resistor', 'datasheet':'~', '_match_pin_regex':False, 'description':'Resistor', 'ref_prefix':'R', 'num_units':1, 'fplist':['R_*'], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'pins':[
            Pin(num='1',name='~',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='~',func=Pin.types.PASSIVE,do_erc=True)] })])